import Content from '@/components/Content';
import Image from 'next/image';
import AboutImage from '@/public/about.jpg';

export const metadata = {
  title: 'About',
  description: 'Generated by create next app',
};


export default function About() {
  return (
    <div className="h-screen">
      <div className="h-full">
        <Content image={AboutImage} text="Welcome to about page!!!!" />
      </div>
    </div>
  );
}
